# Site settings
title: Abulla | A Data Science  blog
description: "A minimal blog template, build with Jekyll."
url: "https://github.com/abelothow/abelothow"
author:
  name: "Abulla Othow"
  email: "getabelothow.com"
  url: "https://github.com/abelothow"

# Build settings
baseurl: /blog # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
